/// Flutter icons SportIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SportIcons
///      fonts:
///       - asset: fonts/SportIcons.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class SportIcons {
  SportIcons._();

  static const _kFontFam = 'SportIcons';
  static const _kFontPkg = null;

  static const IconData row = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bicycle = IconData(0xf206, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dumbbell = IconData(0xf44b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData walk = IconData(0xf554, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swim = IconData(0xf5c4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hike = IconData(0xf6ec, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData run = IconData(0xf70c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skate = IconData(0xf7c5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ski = IconData(0xf7c9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ski_nordic = IconData(0xf7ca, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snowboard = IconData(0xf7ce, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
