/// Flutter icons SyncLogo
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SyncLogo
///      fonts:
///       - asset: fonts/SyncLogo.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class SyncLogo {
  SyncLogo._();

  static const _kFontFam = 'SyncLogo';
  static const _kFontPkg = null;

  static const IconData dropbox = IconData(0xf16b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google_drive = IconData(0xf3aa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData strava = IconData(0xf428, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
