name: Build and make Release
on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  build:
    name: Build Android package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8
      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git -b beta --depth 1 ~/.flutter_dist
          yes | ~/.flutter_dist/bin/flutter doctor --android-licenses
      - name: 'Set environment'
        id: set_env
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/v}
          echo ::set-output name=BUILD_NUMBER::`date +%s`
          echo ::set-output name=NDK_VERSION::`/usr/local/lib/android/sdk/tools/bin/sdkmanager --list | grep ndk-bundle | gawk 'match($0, /[0-9\.]+/, gr) {print gr[0]; exit}'`
      - name: Build Android bundle
        env:
          ORG_GRADLE_PROJECT_keyPassword: ${{ secrets.PLAY_STORE_KEY_PASSWORD }}
          ORG_GRADLE_PROJECT_ndkVersion: ${{ steps.set_env.outputs.NDK_VERSION }}
          ORG_GRADLE_PROJECT_strava_client_id: ${{ secrets.SECRET_STRAVA_CLIENT_ID }}
          ORG_GRADLE_PROJECT_strava_client_secret: ${{ secrets.SECRET_STRAVA_CLIENT_SECRET }}
          ORG_GRADLE_PROJECT_dropbox_client_id: ${{ secrets.SECRET_DROPBOX_CLIENT_ID }}
          ORG_GRADLE_PROJECT_dropbox_client_secret: ${{ secrets.SECRET_DROPBOX_CLIENT_SECRET }}
        run: ~/.flutter_dist/bin/flutter build appbundle --build-name=${{ steps.set_env.outputs.SOURCE_TAG }} --build-number=${{ steps.set_env.outputs.BUILD_NUMBER }}
      - name: Deploy to Play Store internal track using Fastlane
        uses: maierj/fastlane-action@v1.4.0
        env:
          SUPPLY_PACKAGE_NAME: org.fitrecord.android.release
          SUPPLY_VERSION_NAME: ${{ steps.set_env.outputs.SOURCE_TAG }}
          SUPPLY_VERSION_CODE: ${{ steps.set_env.outputs.BUILD_NUMBER }}
          SUPPLY_TRACK: internal
          SUPPLY_JSON_KEY_DATA: ${{ secrets.PLAY_STORE_KEY_JSON }}
          SUPPLY_AAB: ../build/app/outputs/bundle/release/app-release.aab
        with:
          lane: deploy
          subdirectory: android
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.set_env.outputs.SOURCE_TAG }}
          draft: false
          prerelease: true
      - name: Upload Release Asset 
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/app/outputs/bundle/release/app-release.aab
          asset_name: android-bundle-${{ steps.set_env.outputs.SOURCE_TAG }}.aab
          asset_content_type: 'application/octet-stream'