name: Build and make Release
on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  build:
    name: Build Android package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: set up JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8
      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git -b beta --depth 1 ~/.flutter_dist
          ~/.flutter_dist/bin/flutter doctor --android-licenses
      - name: Build Android bundle
        run: ~/.flutter_dist/bin/flutter build appbundle
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: true
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/app/outputs/bundle/release/app.aab
          asset_name: android-bundle.aab
